magephp:
    environments:
        production:
            user: ubuntu
            branch: develop
            from: ./
            ssh:
                port: 2707
            host_path: /home/ubuntu/persotest
            releases: 4
            exclude:
                - ./var/cache/*
                - ./var/log/*
                - ./web/app_dev.php
            hosts:
                - salique
            pre-deploy:
                - exec: { cmd: 'sudo update-alternatives --set php /usr/bin/php8.1', desc: 'Switch to PHP 8.1' }
                - git/update
                - composer/install
                - composer/dump-autoload
            on-deploy:
                - symfony/cache-warmup: { env: 'dev' }
                - symfony/assets-install: { env: 'dev' }
            on-release:
            post-release:
            post-deploy:
                - yarn install
                - yarn run build
                - exec: { cmd: 'sudo update-alternatives --set php /usr/bin/php7.4', desc: 'Switch to PHP 7.4' }
