magephp:
    environments:
        production:
            user: ubuntu
            branch: develop
            from: ./
            ssh:
                port: 2707
            host_path: /home/ubuntu/personal-library
            releases: 4
            exclude:
                - ./var/cache/*
                - ./var/log/*
                - ./web/app_dev.php
            hosts:
                - salique
            pre-deploy:
                - git/update
                - composer/install
                - composer/dump-autoload
            on-deploy:
                - exec: { cmd: 'sudo update-alternatives --set php /usr/bin/php8.1', desc: 'Switch to PHP 8.1' }
                - symfony/cache-warmup: { env: 'prod' }
                - symfony/assets-install: { env: 'prod', target: 'public' }
                - exec: { cmd: 'sudo update-alternatives --set php /usr/bin/php7.4', desc: 'Switch to PHP 7.4' }
            on-release:
            post-release:
            post-deploy:
                - exec: { cmd: 'sudo systemctl reload php8.1-fpm.service', desc: 'Reload PHP 8.1 FPM' }
