version: '3'
services:
    apache:
        build: .docker/apache
        container_name: apache
        ports:
            - "8099:80"
        volumes:
            - ./.docker/conf:/etc/apache2/sites-enabled
            - .:/var/www/personal-library
        depends_on:
          - php74
    db:
      image: mysql:8
      container_name: db
      ports:
        - "3307:3306"
      command:
          - "--default-authentication-plugin=mysql_native_password"
          - "--lower_case_table_names=1"
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: madb
          MYSQL_USER: monuser
          MYSQL_PASSWORD: monpass
      volumes:
        - ./.docker/mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8086:80"
        links:
            - db
        environment:
          PMA_HOST: db

    php74:
        build: ./.docker/php74
        container_name: php74
        depends_on:
          - db
        volumes:
            - .:/var/www/personal-library
